### PR TITLE
Add OCaml 4.08 support

### PR DESCRIPTION
**Pull request by XVilka**

### CODE REVIEW

**Comment by XVilka** [comment]
Also, since there is a  long time error for OCaml 4.03 and OCaml 4.04 versions, maybe it makes sense to drop their support? After all they were released long time ago, 4.08 is out, and 4.09 will be ready quite soon as well...
```
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+ /home/travis/.opam/opam-init/hooks/sandbox.sh "build" "dune" "subst" (CWD=/home/travis/.opam/ocaml-base-compiler.4.03.0/.opam-switch/build/asn1-combinators.0.2.0)
+ /home/travis/.opam/opam-init/hooks/sandbox.sh "build" "dune" "build" "-p" "asn1-combinators" "-j" "1" (CWD=/home/travis/.opam/ocaml-base-compiler.4.03.0/.opam-switch/build/asn1-combinators.0.2.0)
-       ocamlc src/.asn1_combinators.objs/byte/asn_combinators.{cmi,cmo,cmt} (exit 2)
- (cd _build/default && /home/travis/.opam/ocaml-base-compiler.4.03.0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.asn1_combinators.objs/byte -I src/.asn1_combinators.objs/public_cmi -I /home/travis/.opam/ocaml-base-compiler.4.03.0/lib/bigarray-compat -I /home/travis/.opam/ocaml-base-compiler.4.03.0/lib/cstruct -I /home/travis/.opam/ocaml-base-compiler.4.03.0/lib/ptime -I /home/travis/.opam/ocaml-base-compiler.4.03.0/lib/result -I /home/travis/.opam/ocaml-base-compiler.4.03.0/lib/zarith -no-alias-deps -o src/.asn1_combinators.objs/byte/asn_combinators.cmo -c -impl src/asn_combinators.ml)
- File "src/asn_combinators.ml", line 94, characters 16-34:
- Error: Unbound value M2.max_binding_opt
[ERROR] The compilation of asn1-combinators failed at
        "/home/travis/.opam/opam-init/hooks/sandbox.sh build dune build -p
        asn1-combinators -j 1".
#=== ERROR while compiling asn1-combinators.0.2.0 =============================#
# context     2.0.3 | linux/x86_64 | ocaml-base-compiler.4.03.0 | pinned(file:///home/travis/build/mirleft/ocaml-asn1-combinators)
# path        ~/.opam/ocaml-base-compiler.4.03.0/.opam-switch/build/asn1-combinators.0.2.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p asn1-combinators -j 1
# exit-code   1
# env-file    ~/.opam/log/asn1-combinators-24700-ffb3fd.env
# output-file ~/.opam/log/asn1-combinators-24700-ffb3fd.out
### output ###
#       ocamlc src/.asn1_combinators.objs/byte/asn_combinators.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/travis/.opam/ocaml-base-compiler.4.03.0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.asn1_combinators.objs/byte -I src/.asn1_combinators.objs/public_cmi -I /home/travis/.opam/ocaml-base-compiler.4.03.0/lib/bigarray-compat -I /home/travis/.opam/ocaml-base-compiler.4.03.0/lib/cstruct -I /home/travis/.opam/ocaml-base-compiler.4.03.0/lib/ptime -I /home/travis/.opam/ocam[...]
# File "src/asn_combinators.ml", line 94, characters 16-34:
# Error: Unbound value M2.max_binding_opt
```

**Comment by XVilka** [comment]
Nevermind, not a portable solution across OCaml versions.

**Comment by XVilka** [comment]
OK, should be fine after https://github.com/mirleft/ocaml-asn1-combinators/pull/27 is merged and https://github.com/mirleft/ocaml-asn1-combinators/issues/30 is fixed.

**Comment by hannesm** [comment]
thanks, this is supeerseeded by #31

**Pull request closed without merging**
