### PR TITLE
Fix random_time_tests on 32-bit platforms

### LINKED ISSUE #13: Test failure on i686
The test suite fails on i686 (i.e., 32 bits architecture), see [log](http://hydra.nixos.org/build/25030638/nixlog/1).

The error comes from [`random_time_tests`](https://github.com/mirleft/ocaml-asn1-combinators/blob/master/tests/testlib.ml#L105), with `t = 2780622788.` and `t' = -2147483648.` and originates from the behaviour of `Unix.gmtime` which returns `{Unix.tm_sec = 8; tm_min = 13; tm_hour = 3; tm_mday = 11; tm_mon = 1; tm_year = 158; tm_wday = 1; tm_yday = 41; tm_isdst = false}` on x86_64 and `{Unix.tm_sec = 52; tm_min = 45; tm_hour = 20; tm_mday = 13; tm_mon = 11;             tm_year = 1; tm_wday = 5; tm_yday = 346; tm_isdst = false}` on i686.

This may relate to the Year 2038 bug and be an issue with the test suite (rather than with the code being tested): `Unix.gmtime` should not be called with random overflowing values.

### PR DESCRIPTION
**Pull request by sternenseemann**
This resolves #13.

### CODE REVIEW

**Comment by sternenseemann** [comment]
A release with this commit would also be pretty cool, so we don't have to patch the package in @NixOS…

**Comment by pqwy** [comment]
Thx, fixed in e5836188f03c169561f5643ef4f5241f4fb6b6de. Will rel.

**Comment by pqwy** [comment]
@sternenseemann Fixed tests will be in [0.1.3](https://github.com/ocaml/opam-repository/pull/7808).

**Comment by sternenseemann** [comment]
Thank you, awesome!

**Pull request closed without merging**
